package com.uam.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * A detected Segregation of Duties conflict for a user.
 * Generated by the SoD engine when a user holds conflicting role/permission
 * combinations simultaneously.
 */
@Entity
@Table(name = "sod_violations",
    indexes = {
        @Index(name = "idx_sod_user",   columnList = "user_id"),
        @Index(name = "idx_sod_status", columnList = "status"),
    })
@Data
@NoArgsConstructor
@AllArgsConstructor
public class SodViolation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Human-readable label for the conflicting rule */
    @Column(nullable = false, length = 200)
    private String ruleName;

    /** First role or permission in the conflict */
    @Column(nullable = false, length = 100)
    private String conflictA;

    /** Second role or permission in the conflict */
    @Column(nullable = false, length = 100)
    private String conflictB;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 15)
    private SodSeverity severity;

    @Column(length = 500)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ViolationStatus status;

    /** Who approved the exception (if any) */
    @Column(length = 50)
    private String approvedBy;

    /** Business justification for the exception */
    @Column(length = 500)
    private String justification;

    private LocalDateTime detectedAt;
    private LocalDateTime resolvedAt;

    @PrePersist
    void prePersist() {
        detectedAt = LocalDateTime.now();
        if (status == null) status = ViolationStatus.OPEN;
    }

    public enum SodSeverity  { LOW, MEDIUM, HIGH, CRITICAL }
    public enum ViolationStatus { OPEN, ACCEPTED, MITIGATED, RESOLVED }
}
